version: "3.8"
services:
  backend:
    build: ./Backend
    container_name: backend
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
<<<<<<< HEAD
    env_file:
      - .env
=======
>>>>>>> cleanup-pycache

  frontend:
    build: ./Frontend
    container_name: frontend
    volumes:
      - .:/workspace
    ports:
      - "3000:3000"
    depends_on:
      - backend
<<<<<<< HEAD
    command: npm start
    
=======
>>>>>>> cleanup-pycache
