services:
  backend:
    profiles: ["backend"]   # ðŸ‘ˆ add this
    build:
      context: ./Backend
    container_name: ecommerce_backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./Backend:/my_project/Backend
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    profiles: ["frontend"]   # ðŸ‘ˆ add this
    build:
      context: ./Frontend
    container_name: ecommerce_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./Frontend:/my_project/Frontend
    command: ["npm", "start"]
