version: '3.9'

services:
  backend:
    build:
      context: ./Backend
    container_name: ecommerce_backend
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/my_project/Backend
    restart: unless-stopped
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./Frontend
    container_name: ecommerce_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://<EC2_PUBLIC_IP>:8000
    volumes:
      - ./Frontend:/my_project/Frontend
    restart: unless-stopped
